[package]
name = "macro_common"
version = "0.1.0"
edition = "2021"

[features]
verbose = []

[dependencies]
syn = { version = "^1", features = ["full", "parsing", "extra-traits"] }
quote = { version = "^1" }
proc-macro2 = { version = "^1" }
